---
services:
  buildproject:
    image: maven:3.8-openjdk-11 #andresarm/agent
    container_name: bild-war
    command: >
      sh -c "
      git clone https://github.com/shephertz/App42PaaS-Java-MySQL-Sample.git && 
      cd ./App42PaaS-Java-MySQL-Sample && 
      mkdir -p target && 
      mvn package -DskipTests &&
      cp ./target/*.war /tmp 
      "
    volumes:
      - /tmp:/tmp

