---
version: '3.8'

services:
  buildproject:
    image: maven:3.8-openjdk-11
    container_name: bild-war
    command: >
      sh -c "
      git clone https://github.com/wipefree/App42PaaS-Java-MySQL-Sample.git &&
      cd ./App42PaaS-Java-MySQL-Sample &&
      mkdir -p target && 
      mvn package -DskipTests &&
      cp ./target/*.war /tmp/mysql_app.war && 
      mkdir -p /tmp/content/ && 
      cp ./WebContent/Config.properties /tmp/content/
      "
    networks:
      - app-network
    volumes:
      - /tmp:/tmp

  tomcat:
    image: tomcat:9.0.111-jre21-temurin-jammy
    container_name: deploy
    depends_on:
      buildproject:
        condition: service_completed_successfully
    command: >
      sh -c "
      cp /tmp/mysql_app.war /usr/local/tomcat/webapps/ &&
      mkdir -p /usr/local/tomcat/ROOT/ && 
      cp /tmp/content/Config.properties /usr/local/tomcat/ROOT/ && 
      /usr/local/tomcat/bin/catalina.sh run
      "
    networks:
      - app-network
    ports:
      - 8080:8080
    volumes:
      - /tmp:/tmp

  mysqldb:
    image: mariadb:latest
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: qwerty
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
