---
services:
  buildproject:
    image: maven:3.8-openjdk-11 #andresarm/agent
    container_name: bild-war
    command: >
      sh -c "
      git clone https://github.com/wipefree/Java-MySQL-Sample.git && 
      cd ./Java-MySQL-Sample && 
      mkdir -p target && 
      mvn package -DskipTests &&
      cp ./target/*.war /tmp/mysql_app.war
      "
    volumes:
      - /tmp:/tmp

  tomcat:
    image: andresarm/deploy:tomcat-v1
    container_name: deploy
    depends_on:
      buildproject:
        condition: service_completed_successfully
    #restart: always
    command: >
      sh -c "
      cp /tmp/mysql_app.war /opt/tomcat9/webapps/ &&
      /opt/tomcat9/bin/catalina.sh run
      "
    ports:
      - 8080:8080
    volumes:
      - /tmp:/tmp

  dbapp:
    image: mysql:8.0-debian
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: qwerty
    ports:
      - 3306:3306
    #volumes:
    #  - mysql_data:/var/lib/mysql

#volumes:
#  mysql_data:
