---
services:
  buildproject:
    image: maven:3.8-openjdk-11 #andresarm/agent
    container_name: bild-war
    command: >
      sh -c "
      git clone https://github.com/shephertz/App42PaaS-Java-MySQL-Sample.git && 
      cd ./App42PaaS-Java-MySQL-Sample && 
      mkdir -p target && 
      mvn package -DskipTests &&
      cp ./target/*.war /tmp/mysql_app.war
      "
    volumes:
      - /tmp:/tmp

  tomcat:
    image: andresarm/deploy:tomcat-v1
    container_name: deploy
    depends_on:
      buildproject:
        condition: service_completed_successfully
    #restart: always
    command: >
      sh -c "
      cp /tmp/mysql_app.war /opt/tomcat9/webapps/ &&
      catalina.sh run
      "
    ports:
      - 8080:8080
    volumes:
      - /tmp:/tmp
